# Generated by Django 3.2.16 on 2024-03-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='full_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
