# Generated by Django 3.2.16 on 2024-03-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='full_price',
            field=models.PositiveIntegerField(),
        ),
    ]
